### ISSUE TITLE
BT 4.0 HID string to HID

### ISSUE THREAD

**Issue by Netoperz** [rampadc/cc254x-hidKbdM#2]
Hello, i have got one question, is it possible to send string to the UART RX of the module with this firmware, using for example in arduino  Serial.print("SOME STRING YOU WANT");   ?

I have got a project, where i have to send some numbers and letters (hexadecimal) over serial, to the module, and make an input to the target application on host device. 
For example to fill in the form, just like writing on keyboard.
So i need HID, but some hid keyboard modules do not have such a functionality as they are tended to read keystroke matrix without possibility to send string from serial (UART)

I'm asking here, because buying a programmer just for testing "is it working or not" makes no sense, but if it will work that way i'll buy :)

Waiting for some info about it.

Also i could use HC06 BT 2.0 and flash it with HID firmware but I can't find anywhere the hid firmware duped from hid version of that cSR module, so your bt 4.0 looks more interesting.

**Comment by rampadc** [comment]
Translation mode is what you need.
